import type { Metadata } from "next";
import "../../globals.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import StoreProvider from "../storeProvider";
import NavBar from "@/components/nav-bar/NavBar";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={cn(
          "min-h-screen w-full flex flex-col items-center antialiased"
        )}
      >
        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            {/* NavBar fixed at the top */}
            <div className="fixed top-0 left-0 right-0 z-50">
              <NavBar />
            </div>

            {/* Main content grid layout */}
            <main>
              <div>{children}</div>
            </main>
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
