import type { Metadata } from "next";
import "../../globals.css";
import "@radix-ui/themes/styles.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import StoreProvider from "../storeProvider";
import NavBar from "@/components/nav-bar/NavBar";
import { cn } from "@/lib/utils";
import { Theme, ThemePanel } from "@radix-ui/themes";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body
        className={cn(
          "min-h-screen w-full flex flex-col items-center antialiased"
        )}
      >
        <Theme>
          <NextIntlClientProvider messages={messages}>
            <StoreProvider>
              {/* NavBar fixed at the top */}
              <div className="fixed top-0 left-0 right-0 z-50">
                <NavBar />
              </div>

              {/* Main content grid layout */}
              <main className="pt-20 px-4 sm:px-6 lg:px-8">
                <div
                  className={cn(
                    "grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4",
                    "auto-rows-max justify-items-center items-start"
                  )}
                >
                  {children}
                </div>
              </main>
            </StoreProvider>
          </NextIntlClientProvider>
          {/* <ThemePanel /> */}
        </Theme>
      </body>
    </html>
  );
}
