import type { Metadata } from "next";
import "../../globals.css";
import "@radix-ui/themes/styles.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import StoreProvider from "../storeProvider";
import NavBar from "@/components/nav-bar/NavBar";
import { useTranslations } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <StoreProvider>
            {/* NavBar fixed at the top */}
            <NavBar />

            {/* Main content */}
            <main className="bg-background">{children}</main>

            {/* Footer at the bottom end*/}
            <FooterWrapper />
          </StoreProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}

const FooterWrapper: React.FC = () => {
  const t = useTranslations("footer");
  return (
    <div className="bg-primary-variant text-muted-foreground text-center text-sm">
      &copy; {new Date().getFullYear()} {t("copyright")}
    </div>
  );
};
