import type { Metadata } from "next";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import { getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import StoreProvider from "./storeProvider";
import ClientLayout from "./ClientLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages({ locale: params.locale });

  return (
    <html lang={params.locale}>
      <body>
        <NextIntlClientProvider messages={messages}>
          <ClientLayout>
            <StoreProvider>
              <main className="bg-background">{children}</main>
            </StoreProvider>
          </ClientLayout>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
